services:
  web:
    build:
      context: ../../../
      dockerfile: ./dockerfiles/nest/tiamatrestaurante
      args:
        - INICIALES=tiamat
    container_name: cttiamatrestaurante
    image: kuklusklan/restaurante_backend01
    ports:
      - 3000:3000
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs
    networks:
      pnginx_network:
        ipv4_address: 192.168.23.3
networks:
  pnginx_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}