services:
  web:
    build:
      context: /home/TiamatV1/proyecto_tfg/docker/megacrossover/
      dockerfile: ./dockerfiles/nginxrestaurante/tiamatnginxrestaurante
      args:
        - INICIALES=tiamat
    container_name: cttiamatfrontend01
    image: TiamatV1/restaurante_frontend01
    ports:
      - 3000:3000
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs
    networks:
      pnginx_network:
        ipv4_address: 192.168.23.3
networks:
  pnginx_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}