FROM kuklusklan/nginx101

# Instalar Node.js 22
RUN apt-get update && apt-get install -y curl gnupg software-properties-common
RUN apt-get install -y curl ca-certificates gnupg
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
RUN apt-get install -y nodejs
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*
RUN node --version && npm --version

# Crear directorio para el proyecto Next.js
RUN mkdir -p /root/admin/node/proyectos/next_app
WORKDIR /root/admin/node

# Copiar el proyecto Next.js
COPY ./proyecto/next_app/ /root/admin/node/proyectos/next_app/

# Copiar el script de entrypoint
COPY ./dockerfiles/next/admin/start.sh .
RUN chmod +x /root/admin/node/start.sh

ENTRYPOINT ["./start.sh"]
